name: molapp
channels:
  - rdkit
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - rdkit
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip
  - pip:
      - streamlit
      - torch-geometric
      - scikit-learn
      - pandas